---
- name: Add k8s Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: Add k8s source repository into sources list
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    filename: kubernetes

- name: Install k8s packages
  apt:
    force_apt_get: yes
    name:
      - kubeadm={{ kubernetes_version }}
      - kubelet={{ kubernetes_version }}
      - kubectl={{ kubernetes_version }}
  ignore_errors: "{{ ansible_check_mode }}"
  notify:
    - reboot_server
    
- name: Prevent k8s packages from being upgraded
  dpkg_selections:
    name: "{{ item }}"
    selection: hold
  with_items:
    - kubeadm
    - kubelet
    - kubectl

- name: Disable swap
  command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Delete swapfile from /etc/fstab
  mount:
    path: none
    fstype: swap
    state: absent

- name: Ensure KUBELET_EXTRA_ARGS is set
  lineinfile:
    path: /etc/default/kubelet
    regexp: '^#?KUBELET_EXTRA_ARGS'
    line: 'KUBELET_EXTRA_ARGS=--cgroup-driver=systemd'
    create: yes
