---
- name: Templat a file to /etc/modules-load.d/containerd.conf
  template:
    src: containerd.conf.j2
    dest: /etc/modules-load.d/containerd.conf

- name: Add modules
  modprobe:
    name: "{{ item }}"
  with_items:
      - overlay
      - br_netfilter

- name: Set parameters in /etc/sysctl.d/99-kubernetes-cri.conf
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes
  with_items:
    - name: net.bridge.bridge-nf-call-iptables
      value: 1
    - name: net.ipv4.ip_forward
      value: 1
    - name: net.bridge.bridge-nf-call-ip6tables
      value: 1

- name: Install packages for setting up repository
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
  ignore_errors: "{{ ansible_check_mode }}"

- name: Add docker apt signing key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add docker repository into sources list
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ containerd_lsb_release }} stable"
    filename: containerd

- name: Update all repositories cache
  apt:
    force_apt_get: yes
    update_cache: yes
  changed_when: False

- name: Install containerd package
  apt:
    force_apt_get: yes
    name: "containerd.io={{ containerd_version }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Prevent k8s packages from being upgraded
  dpkg_selections:
    name: containerd.io
    selection: hold

- name: Templat a file to /etc/containerd/config.toml
  template:
    src: config.toml.j2
    dest: /etc/containerd/config.toml
  notify: restart_service

- name: Enable and start cri-o service
  systemd:
    name: containerd
    state: started
    enabled: yes
    daemon_reload: yes
